version: 2.1

executors:
  node-jdk-executor:
    docker:
      - image: circleci/node:latest
      - image: circleci/openjdk:8-jdk
    working_directory: ~/appjam-ai

jobs:
  build:
    executor: node-jdk-executor
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
    steps:
      # checks out repo
      - checkout
      # restores cache (gcloud sdk, uglifyjs, ant, jdk)
      - restore_cache:
          keys:
          - deps-{{ checksum ".circleci/install-deps.sh" }}
      # downloads and configures gcloud sdk. installs uglifyjs
      - run: 
          name: Download and configure gcloud sdk, installs uglifyjs
          command: /bin/bash .circleci/install-deps.sh
      # saves cache (gcloud sdk, uglifyjs installation)
      - save_cache:
          paths:
            - ~/google-cloud-sdk
          key: deps-{{ checksum ".circleci/install-deps.sh" }}
      # installs submodule (blocky), creates AuthKey and builds binary
      - run:
          name: Install submodules, create AuthKey and build Binary
          command: make init
      # saves to workspace
      - persist_to_workspace:
          root: ~/
          paths:
              - appjam-ai
  deploy:
    executor: node-jdk-executor
    steps:
      # checks out workspace
      - attach_workspace:
          at: ~/appjam-ai
      # restores cache (gcloud sdk, uglifyjs, ant, jdk)
      - restore_cache:
          keys:
          - deps-{{ checksum ".circleci/install-deps.sh" }}
      # downloads and configures gcloud sdk. installs uglifyjs
      - run: 
          name: Download and configure gcloud sdk, installs uglifyjs
          command: /bin/bash .circleci/install-deps.sh
      # saves cache (gcloud sdk, uglifyjs installation)
      - save_cache:
          paths:
            - ~/google-cloud-sdk
          key: deps-{{ checksum ".circleci/install-deps.sh" }}
      # deploys to google app engine
      - run:
          name: Deploy to GAE
          command: ~/google-cloud-sdk/bin/gcloud -q app deploy appinventor/appengine/build/war/WEB-INF/appengine-web.xml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
